### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by Hohenzoller** [Shubhamrawat5/apple-playlist-downloader-webapp#2]
Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by Shubhamrawat5** [comment]
This application is no longer in heroku. It's in render

New link is
https://apple-playlist-downloader-pvx.onrender.com/

**Comment by BilliBoleMeow** [comment]
> This application is no longer in heroku. It's in render
> 
> New link is https://apple-playlist-downloader-pvx.onrender.com/

No longer working, always no songs found , tried many playlist

**Comment by Shubhamrawat5** [comment]
I think there is problem with web scraping of playlist data. Will check and try to fix

**Comment by Shubhamrawat5** [comment]
It should be working now.
